version: '3.8'

services:
  mongo:
    # image: mongo:4.4
    # image: mongo:latest
    image: mongodb/mongodb-atlas-local
    container_name: mongo
    ports:
      - "27017:27017"
      # - 27017
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      # - 8081
      - 8081:8081
    environment:
      # - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      # - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
      # - ME_CONFIG_MONGODB_AUTH_PASSWORD=pass
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_SITE_BASEURL=/mongo-express/
    networks:
      - backend

  restapi:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      # - "8000:8000"
      - 8000
    environment:
      - MONGO_DETAILS=mongodb://mongo:27017
    depends_on:
      - mongo
    networks:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_API_ARG: /api
    container_name: react_app
    ports:
      # - "3000:3000"
      - 3000
    depends_on:
      - restapi
    environment:
      - REACT_APP_BACKEND_API=http://fastapi:8000/api
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - restapi
      - frontend
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge
